// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JoeShih716/go-k8s-game-server/internal/core/framework (interfaces: GameHandler)
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/framework/mock_game_handler.go -package=mock_framework github.com/JoeShih716/go-k8s-game-server/internal/core/framework GameHandler
//

// Package mock_framework is a generated GoMock package.
package mock_framework

import (
	context "context"
	reflect "reflect"

	framework "github.com/JoeShih716/go-k8s-game-server/internal/core/framework"
	gomock "go.uber.org/mock/gomock"
)

// MockGameHandler is a mock of GameHandler interface.
type MockGameHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGameHandlerMockRecorder
	isgomock struct{}
}

// MockGameHandlerMockRecorder is the mock recorder for MockGameHandler.
type MockGameHandlerMockRecorder struct {
	mock *MockGameHandler
}

// NewMockGameHandler creates a new mock instance.
func NewMockGameHandler(ctrl *gomock.Controller) *MockGameHandler {
	mock := &MockGameHandler{ctrl: ctrl}
	mock.recorder = &MockGameHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameHandler) EXPECT() *MockGameHandlerMockRecorder {
	return m.recorder
}

// OnJoin mocks base method.
func (m *MockGameHandler) OnJoin(ctx context.Context, session *framework.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnJoin", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnJoin indicates an expected call of OnJoin.
func (mr *MockGameHandlerMockRecorder) OnJoin(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnJoin", reflect.TypeOf((*MockGameHandler)(nil).OnJoin), ctx, session)
}

// OnMessage mocks base method.
func (m *MockGameHandler) OnMessage(ctx context.Context, session *framework.Session, payload []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnMessage", ctx, session, payload)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnMessage indicates an expected call of OnMessage.
func (mr *MockGameHandlerMockRecorder) OnMessage(ctx, session, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnMessage", reflect.TypeOf((*MockGameHandler)(nil).OnMessage), ctx, session, payload)
}

// OnQuit mocks base method.
func (m *MockGameHandler) OnQuit(ctx context.Context, session *framework.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnQuit", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnQuit indicates an expected call of OnQuit.
func (mr *MockGameHandlerMockRecorder) OnQuit(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnQuit", reflect.TypeOf((*MockGameHandler)(nil).OnQuit), ctx, session)
}
