// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JoeShih716/go-k8s-game-server/internal/core/ports (interfaces: ServiceRegistry)
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/core/ports/mock_service_registry.go -package=mock_ports github.com/JoeShih716/go-k8s-game-server/internal/core/ports ServiceRegistry
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	proto "github.com/JoeShih716/go-k8s-game-server/api/proto"
	centralRPC "github.com/JoeShih716/go-k8s-game-server/api/proto/centralRPC"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceRegistry is a mock of ServiceRegistry interface.
type MockServiceRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRegistryMockRecorder
	isgomock struct{}
}

// MockServiceRegistryMockRecorder is the mock recorder for MockServiceRegistry.
type MockServiceRegistryMockRecorder struct {
	mock *MockServiceRegistry
}

// NewMockServiceRegistry creates a new mock instance.
func NewMockServiceRegistry(ctrl *gomock.Controller) *MockServiceRegistry {
	mock := &MockServiceRegistry{ctrl: ctrl}
	mock.recorder = &MockServiceRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRegistry) EXPECT() *MockServiceRegistryMockRecorder {
	return m.recorder
}

// Deregister mocks base method.
func (m *MockServiceRegistry) Deregister(ctx context.Context, leaseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deregister", ctx, leaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deregister indicates an expected call of Deregister.
func (mr *MockServiceRegistryMockRecorder) Deregister(ctx, leaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockServiceRegistry)(nil).Deregister), ctx, leaseID)
}

// Heartbeat mocks base method.
func (m *MockServiceRegistry) Heartbeat(ctx context.Context, leaseID string, load int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, leaseID, load)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockServiceRegistryMockRecorder) Heartbeat(ctx, leaseID, load any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockServiceRegistry)(nil).Heartbeat), ctx, leaseID, load)
}

// Register mocks base method.
func (m *MockServiceRegistry) Register(ctx context.Context, req *centralRPC.RegisterRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServiceRegistryMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockServiceRegistry)(nil).Register), ctx, req)
}

// SelectServiceByGame mocks base method.
func (m *MockServiceRegistry) SelectServiceByGame(ctx context.Context, gameID int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectServiceByGame", ctx, gameID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectServiceByGame indicates an expected call of SelectServiceByGame.
func (mr *MockServiceRegistryMockRecorder) SelectServiceByGame(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectServiceByGame", reflect.TypeOf((*MockServiceRegistry)(nil).SelectServiceByGame), ctx, gameID)
}

// SelectServiceByType mocks base method.
func (m *MockServiceRegistry) SelectServiceByType(ctx context.Context, serviceType proto.ServiceType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectServiceByType", ctx, serviceType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectServiceByType indicates an expected call of SelectServiceByType.
func (mr *MockServiceRegistryMockRecorder) SelectServiceByType(ctx, serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectServiceByType", reflect.TypeOf((*MockServiceRegistry)(nil).SelectServiceByType), ctx, serviceType)
}
