// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JoeShih716/go-k8s-game-server/internal/core/ports (interfaces: RegistryService)
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/core/ports/mock_registry_service.go -package=mock_ports github.com/JoeShih716/go-k8s-game-server/internal/core/ports RegistryService
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	proto "github.com/JoeShih716/go-k8s-game-server/api/proto"
	centralRPC "github.com/JoeShih716/go-k8s-game-server/api/proto/centralRPC"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryService is a mock of RegistryService interface.
type MockRegistryService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryServiceMockRecorder
	isgomock struct{}
}

// MockRegistryServiceMockRecorder is the mock recorder for MockRegistryService.
type MockRegistryServiceMockRecorder struct {
	mock *MockRegistryService
}

// NewMockRegistryService creates a new mock instance.
func NewMockRegistryService(ctrl *gomock.Controller) *MockRegistryService {
	mock := &MockRegistryService{ctrl: ctrl}
	mock.recorder = &MockRegistryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryService) EXPECT() *MockRegistryServiceMockRecorder {
	return m.recorder
}

// CleanupDeadServices mocks base method.
func (m *MockRegistryService) CleanupDeadServices(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupDeadServices", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupDeadServices indicates an expected call of CleanupDeadServices.
func (mr *MockRegistryServiceMockRecorder) CleanupDeadServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDeadServices", reflect.TypeOf((*MockRegistryService)(nil).CleanupDeadServices), ctx)
}

// Deregister mocks base method.
func (m *MockRegistryService) Deregister(ctx context.Context, leaseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deregister", ctx, leaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deregister indicates an expected call of Deregister.
func (mr *MockRegistryServiceMockRecorder) Deregister(ctx, leaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockRegistryService)(nil).Deregister), ctx, leaseID)
}

// Heartbeat mocks base method.
func (m *MockRegistryService) Heartbeat(ctx context.Context, leaseID string, load int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, leaseID, load)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockRegistryServiceMockRecorder) Heartbeat(ctx, leaseID, load any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockRegistryService)(nil).Heartbeat), ctx, leaseID, load)
}

// Register mocks base method.
func (m *MockRegistryService) Register(ctx context.Context, req *centralRPC.RegisterRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockRegistryServiceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRegistryService)(nil).Register), ctx, req)
}

// SelectServiceByGame mocks base method.
func (m *MockRegistryService) SelectServiceByGame(ctx context.Context, gameID int32) (string, proto.ServiceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectServiceByGame", ctx, gameID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(proto.ServiceType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectServiceByGame indicates an expected call of SelectServiceByGame.
func (mr *MockRegistryServiceMockRecorder) SelectServiceByGame(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectServiceByGame", reflect.TypeOf((*MockRegistryService)(nil).SelectServiceByGame), ctx, gameID)
}
