// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KickUserReq 用於請求強制踢除使用者的命令
type KickUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 要踢除的使用者 ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                         // 踢除原因
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 對應的錯誤代碼 (參考 common.ErrorCode)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserReq) Reset() {
	*x = KickUserReq{}
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserReq) ProtoMessage() {}

func (x *KickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserReq.ProtoReflect.Descriptor instead.
func (*KickUserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *KickUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KickUserReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickUserReq) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

// BroadcastReq 用於請求廣播訊息的命令
type BroadcastReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 接收廣播的使用者 ID 列表
	// 若為空列表，表示進行全服廣播 (World Broadcast)
	UserIds       []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Payload       []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                            // 要發送的原始二進位訊息內容
	ServiceFrom   string   `protobuf:"bytes,3,opt,name=service_from,json=serviceFrom,proto3" json:"service_from,omitempty"` // 發起廣播的服務來源 (例如: "mgmt-service")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastReq) Reset() {
	*x = BroadcastReq{}
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReq) ProtoMessage() {}

func (x *BroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReq.ProtoReflect.Descriptor instead.
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BroadcastReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BroadcastReq) GetServiceFrom() string {
	if x != nil {
		return x.ServiceFrom
	}
	return ""
}

// JoinServiceReq 用於請求加入特定服務的命令
type JoinServiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 使用者 ID
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 要加入的服務名稱 (例如: "fishing-service")
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                // 指定房間 ID (選填，若加入特定房間)
	Token         []byte                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                // 加入令牌 (選填，用於驗證)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinServiceReq) Reset() {
	*x = JoinServiceReq{}
	mi := &file_api_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServiceReq) ProtoMessage() {}

func (x *JoinServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServiceReq.ProtoReflect.Descriptor instead.
func (*JoinServiceReq) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *JoinServiceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinServiceReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *JoinServiceReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinServiceReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_api_proto_gateway_proto protoreflect.FileDescriptor

const file_api_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/gateway.proto\x12\agateway\"]\n" +
	"\vKickUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\"f\n" +
	"\fBroadcastReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fservice_from\x18\x03 \x01(\tR\vserviceFrom\"{\n" +
	"\x0eJoinServiceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\fR\x05tokenB:Z8github.com/JoeShih716/go-k8s-game-server/api/proto;protob\x06proto3"

var (
	file_api_proto_gateway_proto_rawDescOnce sync.Once
	file_api_proto_gateway_proto_rawDescData []byte
)

func file_api_proto_gateway_proto_rawDescGZIP() []byte {
	file_api_proto_gateway_proto_rawDescOnce.Do(func() {
		file_api_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)))
	})
	return file_api_proto_gateway_proto_rawDescData
}

var file_api_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_gateway_proto_goTypes = []any{
	(*KickUserReq)(nil),    // 0: gateway.KickUserReq
	(*BroadcastReq)(nil),   // 1: gateway.BroadcastReq
	(*JoinServiceReq)(nil), // 2: gateway.JoinServiceReq
}
var file_api_proto_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_gateway_proto_init() }
func file_api_proto_gateway_proto_init() {
	if File_api_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_gateway_proto_goTypes,
		DependencyIndexes: file_api_proto_gateway_proto_depIdxs,
		MessageInfos:      file_api_proto_gateway_proto_msgTypes,
	}.Build()
	File_api_proto_gateway_proto = out.File
	file_api_proto_gateway_proto_goTypes = nil
	file_api_proto_gateway_proto_depIdxs = nil
}
