// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/proto/routing.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceType 定義了服務的類型，影響路由策略
type ServiceType int32

const (
	ServiceType_UNKNOWN_SERVICE ServiceType = 0 // 未知服務
	ServiceType_STATELESS       ServiceType = 1 // 無狀態服務 (例如: 老虎機, 大廳)，採用輪詢 (Round-Robin) 分發
	ServiceType_STATEFUL        ServiceType = 2 // 有狀態服務 (例如: 捕魚, 對戰)，採用黏性路由 (Sticky Routing)
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "UNKNOWN_SERVICE",
		1: "STATELESS",
		2: "STATEFUL",
	}
	ServiceType_value = map[string]int32{
		"UNKNOWN_SERVICE": 0,
		"STATELESS":       1,
		"STATEFUL":        2,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_routing_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_api_proto_routing_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_routing_proto_rawDescGZIP(), []int{0}
}

// RoutingMetadata 包含路由決策所需的元數據
type RoutingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceType   ServiceType            `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=routing.ServiceType" json:"service_type,omitempty"`                // 服務類型
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`                                    // 目標服務名稱 (例如: "slots-service", "fishing-service")
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                                         // 房間 ID (有狀態服務路由必需，用於鎖定特定 Pod)
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                         // 使用者 ID (可用於一致性雜湊路由)
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 自定義路由標籤 (例如: vip_level, region)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingMetadata) Reset() {
	*x = RoutingMetadata{}
	mi := &file_api_proto_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingMetadata) ProtoMessage() {}

func (x *RoutingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingMetadata.ProtoReflect.Descriptor instead.
func (*RoutingMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingMetadata) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_UNKNOWN_SERVICE
}

func (x *RoutingMetadata) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *RoutingMetadata) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoutingMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoutingMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_api_proto_routing_proto protoreflect.FileDescriptor

const file_api_proto_routing_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/routing.proto\x12\arouting\"\x94\x02\n" +
	"\x0fRoutingMetadata\x127\n" +
	"\fservice_type\x18\x01 \x01(\x0e2\x14.routing.ServiceTypeR\vserviceType\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x126\n" +
	"\x04tags\x18\x05 \x03(\v2\".routing.RoutingMetadata.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*?\n" +
	"\vServiceType\x12\x13\n" +
	"\x0fUNKNOWN_SERVICE\x10\x00\x12\r\n" +
	"\tSTATELESS\x10\x01\x12\f\n" +
	"\bSTATEFUL\x10\x02B:Z8github.com/JoeShih716/go-k8s-game-server/api/proto;protob\x06proto3"

var (
	file_api_proto_routing_proto_rawDescOnce sync.Once
	file_api_proto_routing_proto_rawDescData []byte
)

func file_api_proto_routing_proto_rawDescGZIP() []byte {
	file_api_proto_routing_proto_rawDescOnce.Do(func() {
		file_api_proto_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_routing_proto_rawDesc), len(file_api_proto_routing_proto_rawDesc)))
	})
	return file_api_proto_routing_proto_rawDescData
}

var file_api_proto_routing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_routing_proto_goTypes = []any{
	(ServiceType)(0),        // 0: routing.ServiceType
	(*RoutingMetadata)(nil), // 1: routing.RoutingMetadata
	nil,                     // 2: routing.RoutingMetadata.TagsEntry
}
var file_api_proto_routing_proto_depIdxs = []int32{
	0, // 0: routing.RoutingMetadata.service_type:type_name -> routing.ServiceType
	2, // 1: routing.RoutingMetadata.tags:type_name -> routing.RoutingMetadata.TagsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_routing_proto_init() }
func file_api_proto_routing_proto_init() {
	if File_api_proto_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_routing_proto_rawDesc), len(file_api_proto_routing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_routing_proto_goTypes,
		DependencyIndexes: file_api_proto_routing_proto_depIdxs,
		EnumInfos:         file_api_proto_routing_proto_enumTypes,
		MessageInfos:      file_api_proto_routing_proto_msgTypes,
	}.Build()
	File_api_proto_routing_proto = out.File
	file_api_proto_routing_proto_goTypes = nil
	file_api_proto_routing_proto_depIdxs = nil
}
