// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -destination=../../test/mocks/engine/mock_game_handler.go -package=mock_engine -source=server.go -self_package github.com/JoeShih716/go-k8s-game-server/test/mocks/engine GameHandler
//

// Package mock_engine is a generated GoMock package.
package mock_engine

import (
	context "context"
	reflect "reflect"

	engine "github.com/JoeShih716/go-k8s-game-server/internal/engine"
	gomock "go.uber.org/mock/gomock"
)

// MockGameHandler is a mock of GameHandler interface.
type MockGameHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGameHandlerMockRecorder
	isgomock struct{}
}

// MockGameHandlerMockRecorder is the mock recorder for MockGameHandler.
type MockGameHandlerMockRecorder struct {
	mock *MockGameHandler
}

// NewMockGameHandler creates a new mock instance.
func NewMockGameHandler(ctrl *gomock.Controller) *MockGameHandler {
	mock := &MockGameHandler{ctrl: ctrl}
	mock.recorder = &MockGameHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameHandler) EXPECT() *MockGameHandlerMockRecorder {
	return m.recorder
}

// OnJoin mocks base method.
func (m *MockGameHandler) OnJoin(ctx context.Context, peer *engine.Peer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnJoin", ctx, peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnJoin indicates an expected call of OnJoin.
func (mr *MockGameHandlerMockRecorder) OnJoin(ctx, peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnJoin", reflect.TypeOf((*MockGameHandler)(nil).OnJoin), ctx, peer)
}

// OnMessage mocks base method.
func (m *MockGameHandler) OnMessage(ctx context.Context, peer *engine.Peer, payload []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnMessage", ctx, peer, payload)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnMessage indicates an expected call of OnMessage.
func (mr *MockGameHandlerMockRecorder) OnMessage(ctx, peer, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnMessage", reflect.TypeOf((*MockGameHandler)(nil).OnMessage), ctx, peer, payload)
}

// OnQuit mocks base method.
func (m *MockGameHandler) OnQuit(ctx context.Context, peer *engine.Peer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnQuit", ctx, peer)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnQuit indicates an expected call of OnQuit.
func (mr *MockGameHandlerMockRecorder) OnQuit(ctx, peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnQuit", reflect.TypeOf((*MockGameHandler)(nil).OnQuit), ctx, peer)
}
