// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/proto/connectorRPC/connector.proto

package connectorRPC

import (
	proto "github.com/JoeShih716/go-k8s-game-server/api/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *proto.PacketHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 目標玩家列表 (若為空則可能是針對單一 connection，但在 RPC 層級通常是用 UserID 或 SessionID)
	// 這裡建議支援多個 SessionID 以提升廣播效率
	SessionIds    []string `protobuf:"bytes,2,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	Payload       []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // 原始訊息內容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_api_proto_connectorRPC_connector_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageReq) GetHeader() *proto.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SendMessageReq) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *SendMessageReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          proto.ErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_api_proto_connectorRPC_connector_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResp) GetCode() proto.ErrorCode {
	if x != nil {
		return x.Code
	}
	return proto.ErrorCode(0)
}

type KickReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *proto.PacketHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickReq) Reset() {
	*x = KickReq{}
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickReq) ProtoMessage() {}

func (x *KickReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickReq.ProtoReflect.Descriptor instead.
func (*KickReq) Descriptor() ([]byte, []int) {
	return file_api_proto_connectorRPC_connector_proto_rawDescGZIP(), []int{2}
}

func (x *KickReq) GetHeader() *proto.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *KickReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KickReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KickResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          proto.ErrorCode        `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickResp) Reset() {
	*x = KickResp{}
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResp) ProtoMessage() {}

func (x *KickResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_connectorRPC_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResp.ProtoReflect.Descriptor instead.
func (*KickResp) Descriptor() ([]byte, []int) {
	return file_api_proto_connectorRPC_connector_proto_rawDescGZIP(), []int{3}
}

func (x *KickResp) GetCode() proto.ErrorCode {
	if x != nil {
		return x.Code
	}
	return proto.ErrorCode(0)
}

var File_api_proto_connectorRPC_connector_proto protoreflect.FileDescriptor

const file_api_proto_connectorRPC_connector_proto_rawDesc = "" +
	"\n" +
	"&api/proto/connectorRPC/connector.proto\x12\fconnectorRPC\x1a\x16api/proto/common.proto\"y\n" +
	"\x0eSendMessageReq\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.common.PacketHeaderR\x06header\x12\x1f\n" +
	"\vsession_ids\x18\x02 \x03(\tR\n" +
	"sessionIds\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"8\n" +
	"\x0fSendMessageResp\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.common.ErrorCodeR\x04code\"n\n" +
	"\aKickReq\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.common.PacketHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"1\n" +
	"\bKickResp\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.common.ErrorCodeR\x04code2\x91\x01\n" +
	"\fConnectorRPC\x12J\n" +
	"\vSendMessage\x12\x1c.connectorRPC.SendMessageReq\x1a\x1d.connectorRPC.SendMessageResp\x125\n" +
	"\x04Kick\x12\x15.connectorRPC.KickReq\x1a\x16.connectorRPC.KickRespBNZLgithub.com/JoeShih716/go-k8s-game-server/api/proto/connectorRPC;connectorRPCb\x06proto3"

var (
	file_api_proto_connectorRPC_connector_proto_rawDescOnce sync.Once
	file_api_proto_connectorRPC_connector_proto_rawDescData []byte
)

func file_api_proto_connectorRPC_connector_proto_rawDescGZIP() []byte {
	file_api_proto_connectorRPC_connector_proto_rawDescOnce.Do(func() {
		file_api_proto_connectorRPC_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_connectorRPC_connector_proto_rawDesc), len(file_api_proto_connectorRPC_connector_proto_rawDesc)))
	})
	return file_api_proto_connectorRPC_connector_proto_rawDescData
}

var file_api_proto_connectorRPC_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_connectorRPC_connector_proto_goTypes = []any{
	(*SendMessageReq)(nil),     // 0: connectorRPC.SendMessageReq
	(*SendMessageResp)(nil),    // 1: connectorRPC.SendMessageResp
	(*KickReq)(nil),            // 2: connectorRPC.KickReq
	(*KickResp)(nil),           // 3: connectorRPC.KickResp
	(*proto.PacketHeader)(nil), // 4: common.PacketHeader
	(proto.ErrorCode)(0),       // 5: common.ErrorCode
}
var file_api_proto_connectorRPC_connector_proto_depIdxs = []int32{
	4, // 0: connectorRPC.SendMessageReq.header:type_name -> common.PacketHeader
	5, // 1: connectorRPC.SendMessageResp.code:type_name -> common.ErrorCode
	4, // 2: connectorRPC.KickReq.header:type_name -> common.PacketHeader
	5, // 3: connectorRPC.KickResp.code:type_name -> common.ErrorCode
	0, // 4: connectorRPC.ConnectorRPC.SendMessage:input_type -> connectorRPC.SendMessageReq
	2, // 5: connectorRPC.ConnectorRPC.Kick:input_type -> connectorRPC.KickReq
	1, // 6: connectorRPC.ConnectorRPC.SendMessage:output_type -> connectorRPC.SendMessageResp
	3, // 7: connectorRPC.ConnectorRPC.Kick:output_type -> connectorRPC.KickResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_connectorRPC_connector_proto_init() }
func file_api_proto_connectorRPC_connector_proto_init() {
	if File_api_proto_connectorRPC_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_connectorRPC_connector_proto_rawDesc), len(file_api_proto_connectorRPC_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_connectorRPC_connector_proto_goTypes,
		DependencyIndexes: file_api_proto_connectorRPC_connector_proto_depIdxs,
		MessageInfos:      file_api_proto_connectorRPC_connector_proto_msgTypes,
	}.Build()
	File_api_proto_connectorRPC_connector_proto = out.File
	file_api_proto_connectorRPC_connector_proto_goTypes = nil
	file_api_proto_connectorRPC_connector_proto_depIdxs = nil
}
