// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: api/proto/connectorRPC/connector.proto

package connectorRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectorRPC_SendMessage_FullMethodName = "/connectorRPC.ConnectorRPC/SendMessage"
	ConnectorRPC_Kick_FullMethodName        = "/connectorRPC.ConnectorRPC/Kick"
)

// ConnectorRPCClient is the client API for ConnectorRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectorRPC 定義了 Connector 提供的控制介面
type ConnectorRPCClient interface {
	// SendMessage 單播/多播: 發送訊息給指定玩家
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// Kick 強制踢除玩家
	Kick(ctx context.Context, in *KickReq, opts ...grpc.CallOption) (*KickResp, error)
}

type connectorRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorRPCClient(cc grpc.ClientConnInterface) ConnectorRPCClient {
	return &connectorRPCClient{cc}
}

func (c *connectorRPCClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, ConnectorRPC_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorRPCClient) Kick(ctx context.Context, in *KickReq, opts ...grpc.CallOption) (*KickResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickResp)
	err := c.cc.Invoke(ctx, ConnectorRPC_Kick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorRPCServer is the server API for ConnectorRPC service.
// All implementations must embed UnimplementedConnectorRPCServer
// for forward compatibility.
//
// ConnectorRPC 定義了 Connector 提供的控制介面
type ConnectorRPCServer interface {
	// SendMessage 單播/多播: 發送訊息給指定玩家
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// Kick 強制踢除玩家
	Kick(context.Context, *KickReq) (*KickResp, error)
	mustEmbedUnimplementedConnectorRPCServer()
}

// UnimplementedConnectorRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorRPCServer struct{}

func (UnimplementedConnectorRPCServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedConnectorRPCServer) Kick(context.Context, *KickReq) (*KickResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Kick not implemented")
}
func (UnimplementedConnectorRPCServer) mustEmbedUnimplementedConnectorRPCServer() {}
func (UnimplementedConnectorRPCServer) testEmbeddedByValue()                      {}

// UnsafeConnectorRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorRPCServer will
// result in compilation errors.
type UnsafeConnectorRPCServer interface {
	mustEmbedUnimplementedConnectorRPCServer()
}

func RegisterConnectorRPCServer(s grpc.ServiceRegistrar, srv ConnectorRPCServer) {
	// If the following call panics, it indicates UnimplementedConnectorRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorRPC_ServiceDesc, srv)
}

func _ConnectorRPC_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorRPCServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorRPC_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorRPCServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorRPC_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorRPCServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorRPC_Kick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorRPCServer).Kick(ctx, req.(*KickReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorRPC_ServiceDesc is the grpc.ServiceDesc for ConnectorRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connectorRPC.ConnectorRPC",
	HandlerType: (*ConnectorRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ConnectorRPC_SendMessage_Handler,
		},
		{
			MethodName: "Kick",
			Handler:    _ConnectorRPC_Kick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/connectorRPC/connector.proto",
}
