// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: api/proto/centralRPC/central.proto

package centralRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CentralRPC_Register_FullMethodName   = "/centralRPC.CentralRPC/Register"
	CentralRPC_Heartbeat_FullMethodName  = "/centralRPC.CentralRPC/Heartbeat"
	CentralRPC_Deregister_FullMethodName = "/centralRPC.CentralRPC/Deregister"
	CentralRPC_Login_FullMethodName      = "/centralRPC.CentralRPC/Login"
	CentralRPC_GetRoute_FullMethodName   = "/centralRPC.CentralRPC/GetRoute"
)

// CentralRPCClient is the client API for CentralRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CentralRPC 定義了遊戲服務註冊、發現與玩家驗證的核心功能
type CentralRPCClient interface {
	// Register: 服務啟動時呼叫，註冊自己的地址與負責的遊戲 ID
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat: 定期呼叫，維持服務在 Registry 中的活躍狀態 (Renew TTL)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Deregister: 服務關閉時主動呼叫，立即移除服務 (Graceful Shutdown)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// Login: 玩家連線後第一件事，驗證 Token (尚未實作詳細邏輯)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// GetRoute: 玩家請求進入遊戲時呼叫，取得目標服務地址
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
}

type centralRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewCentralRPCClient(cc grpc.ClientConnInterface) CentralRPCClient {
	return &centralRPCClient{cc}
}

func (c *centralRPCClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, CentralRPC_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralRPCClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CentralRPC_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralRPCClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, CentralRPC_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralRPCClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, CentralRPC_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centralRPCClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, CentralRPC_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CentralRPCServer is the server API for CentralRPC service.
// All implementations must embed UnimplementedCentralRPCServer
// for forward compatibility.
//
// CentralRPC 定義了遊戲服務註冊、發現與玩家驗證的核心功能
type CentralRPCServer interface {
	// Register: 服務啟動時呼叫，註冊自己的地址與負責的遊戲 ID
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat: 定期呼叫，維持服務在 Registry 中的活躍狀態 (Renew TTL)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Deregister: 服務關閉時主動呼叫，立即移除服務 (Graceful Shutdown)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// Login: 玩家連線後第一件事，驗證 Token (尚未實作詳細邏輯)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// GetRoute: 玩家請求進入遊戲時呼叫，取得目標服務地址
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	mustEmbedUnimplementedCentralRPCServer()
}

// UnimplementedCentralRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCentralRPCServer struct{}

func (UnimplementedCentralRPCServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCentralRPCServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCentralRPCServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedCentralRPCServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedCentralRPCServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedCentralRPCServer) mustEmbedUnimplementedCentralRPCServer() {}
func (UnimplementedCentralRPCServer) testEmbeddedByValue()                    {}

// UnsafeCentralRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CentralRPCServer will
// result in compilation errors.
type UnsafeCentralRPCServer interface {
	mustEmbedUnimplementedCentralRPCServer()
}

func RegisterCentralRPCServer(s grpc.ServiceRegistrar, srv CentralRPCServer) {
	// If the following call panics, it indicates UnimplementedCentralRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CentralRPC_ServiceDesc, srv)
}

func _CentralRPC_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralRPCServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralRPC_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralRPCServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralRPC_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralRPCServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralRPC_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralRPCServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralRPC_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralRPCServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralRPC_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralRPCServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralRPC_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralRPCServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CentralRPC_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CentralRPCServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CentralRPC_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CentralRPCServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CentralRPC_ServiceDesc is the grpc.ServiceDesc for CentralRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CentralRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "centralRPC.CentralRPC",
	HandlerType: (*CentralRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CentralRPC_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CentralRPC_Heartbeat_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _CentralRPC_Deregister_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _CentralRPC_Login_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _CentralRPC_GetRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/centralRPC/central.proto",
}
