// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JoeShih716/go-k8s-game-server/internal/app/connector/handler (interfaces: GRPCPool)
//
// Generated by this command:
//
//	mockgen -destination=../../../../test/mocks/handlers/mock_grpc_pool.go -package=mock_handlers . GRPCPool
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGRPCPool is a mock of GRPCPool interface.
type MockGRPCPool struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCPoolMockRecorder
	isgomock struct{}
}

// MockGRPCPoolMockRecorder is the mock recorder for MockGRPCPool.
type MockGRPCPoolMockRecorder struct {
	mock *MockGRPCPool
}

// NewMockGRPCPool creates a new mock instance.
func NewMockGRPCPool(ctrl *gomock.Controller) *MockGRPCPool {
	mock := &MockGRPCPool{ctrl: ctrl}
	mock.recorder = &MockGRPCPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCPool) EXPECT() *MockGRPCPoolMockRecorder {
	return m.recorder
}

// GetConnection mocks base method.
func (m *MockGRPCPool) GetConnection(target string, opts ...grpc.DialOption) (*grpc.ClientConn, error) {
	m.ctrl.T.Helper()
	varargs := []any{target}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConnection", varargs...)
	ret0, _ := ret[0].(*grpc.ClientConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockGRPCPoolMockRecorder) GetConnection(target any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{target}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockGRPCPool)(nil).GetConnection), varargs...)
}
