// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JoeShih716/go-k8s-game-server/internal/app/connector/handler (interfaces: CentralClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../../test/mocks/handlers/mock_central_client.go -package=mock_handlers . CentralClient
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	proto "github.com/JoeShih716/go-k8s-game-server/api/proto"
	centralRPC "github.com/JoeShih716/go-k8s-game-server/api/proto/centralRPC"
	gomock "go.uber.org/mock/gomock"
)

// MockCentralClient is a mock of CentralClient interface.
type MockCentralClient struct {
	ctrl     *gomock.Controller
	recorder *MockCentralClientMockRecorder
	isgomock struct{}
}

// MockCentralClientMockRecorder is the mock recorder for MockCentralClient.
type MockCentralClientMockRecorder struct {
	mock *MockCentralClient
}

// NewMockCentralClient creates a new mock instance.
func NewMockCentralClient(ctrl *gomock.Controller) *MockCentralClient {
	mock := &MockCentralClient{ctrl: ctrl}
	mock.recorder = &MockCentralClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCentralClient) EXPECT() *MockCentralClientMockRecorder {
	return m.recorder
}

// GetRoute mocks base method.
func (m *MockCentralClient) GetRoute(ctx context.Context, gameID int32) (string, proto.ServiceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoute", ctx, gameID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(proto.ServiceType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoute indicates an expected call of GetRoute.
func (mr *MockCentralClientMockRecorder) GetRoute(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoute", reflect.TypeOf((*MockCentralClient)(nil).GetRoute), ctx, gameID)
}

// Login mocks base method.
func (m *MockCentralClient) Login(ctx context.Context, token string) (*centralRPC.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, token)
	ret0, _ := ret[0].(*centralRPC.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockCentralClientMockRecorder) Login(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockCentralClient)(nil).Login), ctx, token)
}
